[colors.primary]
background = '#15130e'
foreground = '#e8e2d9'
 
[colors.cursor]
text = '#e8e2d9'
cursor = '#cfc6b4' 
 
[colors.vi_mode_cursor]
text = '#15130e'
cursor = '#e9c348' 
 
[colors.search.matches]
foreground = '#4c4639' 
background = '#accfae' 
 
[colors.search.focused_match]
foreground = '#4c4639' 
background = '#e9c348' 
 
[colors.footer_bar]
foreground = '#4c4639' 
background = '#e8e2d9' 
 
[colors.hints.start]
foreground = '#4c4639' 
background = '#d4c5a1' 
 
[colors.hints.end]
foreground = '#4c4639' 
background = '#d4c5a1' 
 
[colors.selection]
text = '#15130e'
background = '#e9c348'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#e9c348' 
yellow = '#735c00' 
blue = '#e9c348' 
magenta = '#accfae' 
cyan = '#d4c5a1' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 